const stores = [
  {
    id: 1,
    brandName: "Brand Name",
    status: "hidden",
    search: 505000,
    revenue: 540410,
    avgSearch: 50.36,
    avgRevenue: 88.8,
    tracking: 8,
    mana: 5,
    graphData: "",
  },
  {
    id: 2,
    brandName: "Brand Name",
    status: "hidden",
    search: 505000,
    revenue: 540410,
    avgSearch: 50.36,
    avgRevenue: 88.8,
    tracking: 8,
    mana: 5,
    graphData: "",
  },
  {
    id: 3,
    brandName: "Brand Name",
    status: "unlocked",
    search: 505000,
    revenue: 540410,
    avgSearch: 50.36,
    avgRevenue: 88.8,
    tracking: 8,
    mana: 5,
    graphData: "",
  },
  {
    id: 4,
    brandName: "Brand Name",
    status: "brand",
    search: 505000,
    revenue: 540410,
    avgSearch: 50.36,
    avgRevenue: 88.8,
    tracking: 8,
    mana: 5,
    graphData: "",
  },
  {
    id: 5,
    brandName: "Brand Name",
    status: "hidden",
    search: 505000,
    revenue: 540410,
    avgSearch: 50.36,
    avgRevenue: 88.8,
    tracking: 8,
    mana: 5,
    graphData: "",
  },
  {
    id: 6,
    brandName: "Brand Name",
    status: "brand",
    search: 505000,
    revenue: 540410,
    avgSearch: 50.36,
    avgRevenue: 88.8,
    tracking: 8,
    mana: 5,
    graphData: "",
  },
  {
    id: 7,
    brandName: "Brand Name",
    status: "unlocked",
    search: 505000,
    revenue: 540410,
    avgSearch: 50.36,
    avgRevenue: 88.8,
    tracking: 8,
    mana: 5,
    graphData: "",
  },

  {
    id: 8,
    brandName: "Brand Name",
    status: "unlocked",
    search: 505000,
    revenue: 540410,
    avgSearch: 50.36,
    avgRevenue: 88.8,
    tracking: 8,
    mana: 5,
    graphData: "",
  },
];



const products = [
  {
    id: 1,
    brandName:'Brand Name',
    status: "hidden",
    revenue: 540410,
    avgRevenue: 88.8,
    tracking: 8,
    mana:5,
    date: "Oct 22 , 2022",
    graphData: "",
  },
  {
    id: 2,
    brandName:'Brand Name',
    status: "hidden",
    revenue: 540410,
    avgRevenue: 88.8,
    tracking: 8,
    mana:5,
    date: "Oct 22 , 2022",
    graphData: "",
  },
  {
    id: 3,
    brandName:'Brand Name',
    status: "unlocked",
    revenue: 540410,
    avgRevenue: 88.8,
    tracking: 8,
    mana:5,
    date: "Oct 22 , 2022",
    graphData: "",
  },
  {
    id: 4,
    brandName:'Brand Name',
    status: "brand",
    revenue: 540410,
    avgRevenue: 88.8,
    tracking: 8,
    mana:5,
    date: "Oct 22 , 2022",
    graphData: "",
  },
  {
    id: 5,
    brandName:'Brand Name',
    status: "hidden",
    revenue: 540410,
    avgRevenue: 88.8,
    tracking: 8,
    mana:5,
    date: "Oct 22 , 2022",
    graphData: "",
  },
  {
    id: 6,
    brandName:'Brand Name',
    status: "hidden",
    revenue: 540410,
    avgRevenue: 88.8,
    tracking: 8,
    mana:5,
    date: "Oct 22 , 2022",
    graphData: "",
  },
  {
    id: 7,
    brandName:'Brand Name',
    status: "brand",
    revenue: 540410,
    avgRevenue: 88.8,
    tracking: 8,
    mana:5,
    date: "Oct 22 , 2022",
    graphData: "",
  },
  {
    id: 8,
    brandName:'Brand Name',
    status: "unlocked",
    revenue: 540410,
    avgRevenue: 88.8,
    tracking: 8,
    mana:5,
    date: "Oct 22 , 2022",
    graphData: "",
  },
];



export { stores, products };

